version: '3'

services:
  truman-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000"  # Expo dev server
      - "19001:19001"  # Metro bundler
      - "19002:19002"  # Expo dev tools
      - "37373:37373"  # P2P networking port
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
    volumes:
      - ./frontend:/app/frontend
    network_mode: "host"  # Using host network for P2P functionality
